# Generated by Django 3.0.6 on 2020-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(max_length=200, verbose_name='Reported By')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('date', models.DateTimeField(verbose_name='Date Recieved')),
                ('senders_ip', models.CharField(max_length=200, verbose_name='Senders IP')),
                ('link_ip', models.CharField(max_length=200, verbose_name='Link IP')),
                ('email_message_id', models.CharField(max_length=300, verbose_name='Email Message ID')),
                ('subject_line', models.CharField(max_length=300, verbose_name='Subject Line')),
                ('attachment', models.CharField(max_length=300, verbose_name='Attachment')),
                ('reason', models.CharField(max_length=400, verbose_name='Reason')),
                ('notes', models.CharField(max_length=400, verbose_name='Notes')),
                ('email_from', models.CharField(max_length=300, verbose_name='From')),
                ('action_taken', models.CharField(max_length=400, verbose_name='Action Taken')),
            ],
        ),
    ]
